name: base64filedecoder
description: A simple app to decode base64 binaries from Paco server
version: 0.0.1
homepage: https://www.pacoapp.com
author: bobevans@pacoapp.com

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  json_annotation: ^2.0.0
  image: ^2.1.4
  args: ^1.5.2
  path: ^1.6.4

dev_dependencies:
  build_runner: any
  pedantic: ^1.0.0
  json_serializable: ^2.0.0
  test: ^1.0.0
